FROM python:3.12-slim AS builder

COPY ./ /app

FROM python:3.12-slim

COPY --from=builder /app /app

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]